name: 'LFS-warning'
description: 'Checks file sizes in a Pull Request and warns of large files'
inputs:
  filesizelimit:  # id of input 
    description: 'file size threshold'
    required: true
    default: '5000' # for testing # '10485760' # 10 MB is 10485760 Bytes 
outputs:
  time: # output will be available to future steps 
    description: 'Possible large file(s) detected. Consider using Git-LFS in your repository commits'
runs:
  using: 'node12'
  main: 'dist/index.js'
